### ISSUE TITLE
如果实现一个 vue  组件库

### ISSUE THREAD

**Issue by wuweijia** [wuweijia/wuweijia.github.io#48]
### 为什么要做 ？
1. 公司的业务迭代逐渐平稳，样式多变性逐渐消失，UI模块化已经形成规范。
2. 开发人员不知道已经存在哪些组件，容易出现重复造轮子的情况。
3. 易于管理和维护
4. 独立部署之后UI也可以看到组件库写了哪些组件，方便设计的工作。

#### 1. 可视化
一个组件库一定要有一个可以预览组件的地方
#### 2. 文档
每个组件都要有一个说明文档

**Comment by wuweijia** [comment]
**step 1 生成一个基础框架**  

> 构建vue组件库，直接可以拿来vue-cli初始化一个项目来做架子，一来方便，二来你可以直接测试你写的组件在项目中能不能run的起来。

``` vue init webpack projectname ```

**Comment by wuweijia** [comment]
**step 2 整理文件结构**

> 我们只需要component 用来存放组件 和 pages 可以用来展示组件，其他我们可以先不管，或自行处理

有了写组件的地方，我们就可以开始编写组件了。

**Comment by wuweijia** [comment]
**step 3 写一个组件**
> src/component/button/button.vue  
src/component/button/button.scss  
```vue 
<style lang="scss" scoped>
  @import './button.scss';
</style>
<template>
  <button class="button">{{title}}</button>
</template>
<script>
export default {
  name: 'Button',
  data: () => ({
    title: '这是一个button',
  }),
}
</script>

```
```scss
.button {
  width: 180px;
  height: 60px;
  font-size: 16px;
  line-height: 60px;
  text-align: center;
  color: #fff;
  cursor: pointer;
  background-color: red;
}

```
